name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update submodule to latest
        run: |
          git submodule update --remote --merge
          cd fallback-backend && git checkout main && git pull origin main

      - name: Use cached node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.github_token }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --linux --x64 && npm exec electron-builder -- --publish always --win --x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmuDeck-AppImage
          path: "**/*.AppImage"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EmuDeck-main-windows
          path: "**/*.exe"
